import { Router } from 'express';
import jwt from 'jsonwebtoken';
import { body, validationResult } from 'express-validator';
import User from '../models/User.js';
import { requireAuth } from '../middleware/auth.js';
const router = Router();
const tokenFor = user => jwt.sign({ id: user._id }, process.env.JWT_SECRET, { expiresIn: '7d' });
router.post('/register', [body('name').trim().isLength({ min: 2 }), body('email').isEmail().normalizeEmail(), body('password').isLength({ min: 8 }), body('role').isIn(['customer','owner'])], async (req,res,next) => { try { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(422).json({ message: 'Please correct the highlighted details' }); if (await User.exists({ email: req.body.email })) return res.status(409).json({ message: 'An account with this email already exists' }); const user = await User.create(req.body); res.status(201).json({ token: tokenFor(user), user: { id:user._id, name:user.name, email:user.email, role:user.role } }); } catch(e) { next(e); } });
router.post('/login', [body('email').isEmail().normalizeEmail(), body('password').notEmpty()], async (req,res,next) => { try { const user = await User.findOne({ email:req.body.email }).select('+password'); if (!user || !(await user.comparePassword(req.body.password))) return res.status(401).json({ message:'Invalid email or password' }); res.json({ token:tokenFor(user), user:{ id:user._id,name:user.name,email:user.email,role:user.role } }); } catch(e) { next(e); } });
router.get('/me', requireAuth, (req,res) => res.json({ user:req.user }));
router.patch('/me', requireAuth, [body('name').optional().trim().isLength({ min: 2, max: 70 }), body('phone').optional().trim().isLength({ max: 20 })], async (req,res,next) => { try { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(422).json({ message: 'Please provide valid profile details' }); const updates = {}; if (req.body.name) updates.name = req.body.name; if (typeof req.body.phone === 'string') updates.phone = req.body.phone; const user = await User.findByIdAndUpdate(req.user._id, updates, { new: true, runValidators: true }); res.json({ user }); } catch(e) { next(e); } });
export default router;
